version: 0.0

os: linux

files:
  - source: /
    destination: /tmp/erply_api

permissions:
  - object: /tmp
    owner: root
    group: root
    mode: 777

hooks:
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 180
      runas: root