version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
  build:
    commands:
      - echo Building the go code...
      - go mod tidy
      - go mod vendor
      - go build
      - zip -r erply-api.zip  conf erply-api

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - erply-api.zip

      